ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets cursor line pattern regexp)
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=yellow
ZSH_HIGHLIGHT_STYLES[bracket-error]=fg=red,bold
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=cyan
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=grey
ZSH_HIGHLIGHT_STYLES[globbing]=fg=cyan
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=blue
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=green
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]=fg=yellow
ZSH_HIGHLIGHT_STYLES[default]=fg=172
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=fg=magenta
ZSH_HIGHLIGHT_STYLES[cursor]=standout
ZSH_HIGHLIGHT_STYLES[commandseparator]=fg=012
ZSH_HIGHLIGHT_STYLES[redirection]=fg=015
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=cyan
ZSH_HIGHLIGHT_STYLES[arg0]=fg=yellow
ZSH_HIGHLIGHT_STYLES[comment]=fg=black,bold
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]=fg=124
ZSH_HIGHLIGHT_STYLES[root]=standout
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=055
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=cyan
ZSH_HIGHLIGHT_STYLES[bracket-level-1]=fg=blue,bold
ZSH_HIGHLIGHT_STYLES[bracket-level-2]=fg=green,bold
ZSH_HIGHLIGHT_STYLES[bracket-level-3]=fg=magenta,bold
ZSH_HIGHLIGHT_STYLES[path]=fg=166
ZSH_HIGHLIGHT_STYLES[bracket-level-4]=fg=yellow,bold
ZSH_HIGHLIGHT_STYLES[bracket-level-5]=fg=cyan,bold
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]=fg=cyan
ZSH_HIGHLIGHT_STYLES[rc-quote]=fg=cyan
ZSH_HIGHLIGHT_STYLES[assign]=none
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=yellow
ZSH_HIGHLIGHT_STYLES[path_pathseparator]=fg=123
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]=
ZSH_HIGHLIGHT_STYLES[line]=
ZSH_HIGHLIGHT_STYLES[precommand]=fg=155
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=200
